### ISSUE TITLE
Migrate to VSCode Neovim

### ISSUE THREAD

**Issue by ddnomad** [ddnomad/dotfiles#45]
Due to https://github.com/VSCodeVim/Vim/issues/8157 receiving no attention from the maintainers, [VSCode Vim](https://github.com/VSCodeVim/Vim) extension should be deemed ~~unmaintained~~ unsuitable to rely on for day-to-day work at the moment of writing.

Switch to [VSCode Neovim](https://github.com/vscode-neovim/vscode-neovim) instead and see whether it does the job better.

**Comment by ianchanning** [comment]
They clearly are maintaining VSCodeVim, so this is unfair to the devs. But VSCode Neovim does look very promising, but a much bigger change than VSCodeVim.

**Comment by ddnomad** [comment]
> They clearly are maintaining VSCodeVim, so this is unfair to the devs. But VSCode Neovim does look very promising, but a much bigger change than VSCodeVim.

@ianchanning I guess it depends on a definition of "maintaining", which is rather fuzzy in this instance.

Maintaining a popular open source project is a lot of work and a huge commitment, I totally get it. But when there's a breaking issue that clearly affects a lot of people and the maintainers pay no attention to it for what is already 2 months, I cannot in good faith call the project "maintained", or at least not "well maintained".

All of us most probably have things to do, and fixing a misbehaving piece of tooling without any familiarity with the code base is probably would not be the first item on the list. Especially given the last non-automated pull request was merged back in December.

**Comment by ianchanning** [comment]
> Maintaining a popular open source project is a lot of work and a huge commitment

That's all that matters. They have currently 2666 merged PRs and 4083 closed issues. That's a phenomenal amount of work.

That is very much a massively maintained piece of software - so not fuzzy. As recently as [10th Jan 2023](https://github.com/VSCodeVim/Vim/issues/8202) the maintainer was answering questions.

**Comment by ddnomad** [comment]
> > Maintaining a popular open source project is a lot of work and a huge commitment
> 
> That's all that matters. They have currently 2666 merged PRs and 4083 closed issues. That's a phenomenal amount of work.
> 
> That is very much a massively maintained piece of software - so not fuzzy. As recently as [10th Jan 2023](https://github.com/VSCodeVim/Vim/issues/8202) the maintainer was answering questions.

@ianchanning I've updated the wording to sound less harsh. Hopefully now it represents the state of affairs more accurately.
